config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'top#index'
  get '/top/index'           , to: 'top#index'
  get '/register/index'      , to: 'register#index'
  get '/register_comp/index' , to: 'register_comp#index'
  get '/authentication/index', to: 'authentication#index'
  get '/authentication/index', to: 'authentication#index'
  get '/receipt/index'       , to: 'receipt#index'
  get '/receipt/create'      , to: 'receipt#create'
  get '/receipt/patch'       , to: 'receipt#patch'
  get '/family/index'        , to: 'family#index'
  get '/family/patch'        , to: 'family#patch'
  get '/resetPassword/index' , to: 'reset_password#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  layout "template"
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController

  def index
  end

end

app/controllers/family_controller.rb
class FamilyController < ApplicationController
  layout "dashboard"

  def index
  end

  def patch
  end

end

app/controllers/receipt_controller.rb
class ReceiptController < ApplicationController
  layout "dashboard"

  def index
  end

  def patch
  end

end

app/controllers/register_comp_controller.rb
class RegisterCompController < ApplicationController

  def index
  end

end

app/controllers/register_controller.rb
class RegisterController < ApplicationController

  def index
  end

end

app/controllers/reset_password_controller.rb
class ResetPasswordController < ApplicationController
  layout "dashboard"

  def index
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authentication/index.html.erb
<div class="container auth-container">
  <center>
    <%= image_tag "logo.png", :class => "top-logo" %>
  </center>
  <div align="center">
    <legend class="legend guidance">ログイン</legend>
    <div class="registerForm">
      <form class="form-inline top-form">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="id">
        </div>
      </form>
      <%= form_tag({:controller => "receipt", :action => "index"},
                   {:method => "get", :class => "form-inline top-in-btn-form"}) do %>
        <div class="input-group">
          <input type="password" class="form-control" placeholder="password">
          <span class="input-group-btn">
            <button class="btn btn-primary" type="submit">ログイン</button>
          </span>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/family/index.html.erb
<div class="col-md-7">
  <h3>管理者情報</h3>
  <table class="table table-bordered table-hover family-table">
    <thead>
      <tr class="bg-primary">
        <th>ログインID</th>
        <th>名前</th>
        <th>メールアドレス</th>
        <th class="operation">操作</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>miyoko</td>
        <td>美代子</td>
        <td>miyoko@example.com</td>
        <td class="family-operation">
          <div class="dropdown">
            <span class="glyphicon glyphicon-menu-hamburger family-menu-icon" data-toggle="dropdown"></span>
            <div class="dropdown-menu">
              <li class="family-menu">
                <%= link_to "編集", family_patch_path %>
              </li>
            </div>
          </div>
        </td>
      </tr>
    </tbody>
  </table>
</div>

app/views/family/patch.html.erb
<div class="col-sm-4 col-md-4">
  <div class="container update-family-container">
    <legend class="legend update-family-title">ファミリーの編集</legend>
    <form>
      <div class="row update-family-top-row">
        <div class="form-group col-sm-12 col-md-12 update-id-form">
          <label for="update-id">ログインID</label>
          <div class="row">
            <div class="col-sm-12 col-md-12">
              <input type="text" class="form-control" id="update-id">
            </div>
          </div>
        </div>
        <div class="form-group col-sm-12 col-md-12 update-name-form">
          <label for="update-name-form">名前</label>
          <div class="row">
            <div class="col-sm-12 col-md-12">
              <input type="text" class="form-control" id="update-name">
            </div>
          </div>
        </div>
        <div class="form-group col-sm-12 col-md-12 update-mail-form">
          <label for="update-mail">メールアドレス</label>
          <div class="row">
            <div class="col-sm-12 col-md-12">
              <input type="text" class="form-control" id="update-mail">
            </div>
          </div>
        </div>
      </div>
    </form>
    <%= button_to "決定", {:controller => "family", :action => "index"},
                           :method => "get", :class => "btn btn-primary update-family-btn"%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>pocketMoney</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script type="text/javascript" src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "common/common", media: "all", "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag "dashboard/dashboard", media: "all", "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag "receipt/receipt", media: "all", "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag "receipt/create", media: "all", "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag "receipt/patch", media: "all", "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag "family/family", media: "all", "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag "family/patch", media: "all", "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag "resetPassword/resetPassword", media: "all", "data-turbolinks-track" => true %>
  </head>

  <body>
    <div class="container-flud">
      <div class="row">
        <div class="sm-3 col-md-2 sidebar menu">
          <ul class="nav nav-sidebar nav-bar">
            <div class="logo">
              <%= link_to image_tag("logo.png", {:class => "logo-image"}), receipt_index_path %>
            </div>
            <li class="li-head">
              <%= link_to "レシート", receipt_index_path %>
            </li>
            <li>
              <%= link_to "ファミリー", family_index_path %>
            </li>
            <li>
              <%= link_to "パスワードの変更", resetPassword_index_path %>
            </li>
            <li class="blank"></li>
            <li>
              <%= link_to "ログアウト", top_index_path %>
            </li>
          </ul>
        </div>
        <div class="main">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>

</html>

app/views/layouts/template.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>pocketMoney</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script type="text/javascript" src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "common/common", media: "all", "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag "template/template", media: "all", "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag "top/top", media: "all", "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag "register/register", media: "all", "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag "register/registerComp", media: "all", "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag "authentication/authentication", media: "all", "data-turbolinks-track" => true %>
  </head>

  <body>
    <div class="root">
      <main class="main-content" role="main">
        <%= yield %>
      </main>
    </div>
  </body>

</html>

app/views/receipt/create.html.erb
<div class="col-sm-4 col-md-4">
  <div class="container create-receipt-container">
    <legend class="legend create-receipt-title">レシートの追加</legend>
    <form>
      <div class="row top-row">
        <div class="form-group col-sm-4 col-md-4 month-form">
          <label for="input-month">月</label>
          <div class="row">
            <div class="col-sm-12 col-md-12">
              <input type="text" class="form-control" id="input-month">
            </div>
          </div>
        </div>
        <div class="form-group col-sm-4 col-md-4 money-form">
          <label for="input-money">金額(円)</label>
          <div class="row">
            <div class="col-sm-12 col-md-12">
              <input type="text" class="form-control" id="input-money">
            </div>
          </div>
        </div>
      </div>
      <div class="row lower-row">
        <div class="form-group col-sm-12 col-md-12">
          <label>備考</label>
          <div class="row">
            <div class="col-sm-12 col-md-12">
              <textarea type="text" class="form-control" rows="3"></textarea>
            </div>
          </div>
        </div>
      </div>
    </form>
    <%= button_to "追加", {:controller => "receipt", :action => "index"},
                           :method => "get", :class => "btn btn-primary create-receipt-btn"%>
  </div>
</div>

app/views/receipt/index.html.erb
<div class="col-md-7">
  <%= button_to "レシートの追加", {:controller => "receipt", :action => "create"},
                                   :method => "get", :class => "btn btn-primary btn-lg"%>
  <table class="table table-bordered table-hover receipt-table">
    <thead>
      <tr class="bg-primary">
        <th>月</th>
        <th>金額(円)</th>
        <th>備考</th>
        <th class="operation">操作</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>4月</td>
        <td>25000</td>
        <td>食費</td>
        <td class="receipt-operation">
          <div class="dropdown">
            <span class="glyphicon glyphicon-menu-hamburger receipt-menu-icon" data-toggle="dropdown"></span>
            <div class="dropdown-menu">
              <li class="receipt-menu">
                <%= link_to "編集", receipt_patch_path %>
                <%= link_to "削除", {:controller => "receipt", :action => "index"},
                                     :method => "get" %>  <!-- TODO: confirm を実装する -->
              </li>
            </div>
          </div>
        </td>
      </tr>
      <tr>
        <td>4月</td>
        <td>10000</td>
        <td>生活品</td>
        <td class="receipt-operation">
          <div class="dropdown">
            <span class="glyphicon glyphicon-menu-hamburger receipt-menu-icon" data-toggle="dropdown"></span>
            <div class="dropdown-menu">
              <li class="receipt-menu">
                <%= link_to "編集", receipt_patch_path %>
                <%= link_to "削除", {:controller => "receipt", :action => "index"},
                                     :method => "get" %>  <!-- TODO: confirm を実装する -->
              </li>
            </div>
          </div>
        </td>
      </tr>
    </tbody>
  </table>
</div>

app/views/receipt/patch.html.erb
<div class="col-sm-4 col-md-4">
  <div class="container update-receipt-container">
    <legend class="legend update-receipt-title">レシートの編集</legend>
    <form>
      <div class="row update-receipt-top-row">
        <div class="form-group col-sm-4 col-md-4 update-month-form">
          <label for="update-month">月</label>
          <div class="row">
            <div class="col-sm-12 col-md-12">
              <input type="text" class="form-control" id="update-month">
            </div>
          </div>
        </div>
        <div class="form-group col-sm-4 col-md-4 update-money-form">
          <label for="update-money">金額(円)</label>
          <div class="row">
            <div class="col-sm-12 col-md-12">
              <input type="text" class="form-control" id="update-money">
            </div>
          </div>
        </div>
      </div>
      <div class="row update-receipt-lower-row">
        <div class="form-group col-sm-12 col-md-12 update-desc-form">
          <label>備考</label>
          <div class="row">
            <div class="col-sm-12 col-md-12">
              <textarea type="text" class="form-control" rows="3"></textarea>
            </div>
          </div>
        </div>
      </div>
    </form>
    <%= button_to "決定", {:controller => "receipt", :action => "index"},
                           :method => "get", :class => "btn btn-primary update-receipt-btn"%>
  </div>
</div>

app/views/register/index.html.erb
<div class="container register-container">
  <center>
    <%= image_tag "logo.png", :class => "top-logo" %>
  </center>
  <div align="center">
    <legend class="legend guidance">新規登録</legend>
    <div class="registerForm">
      <form class="form-inline top-form">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="id">
        </div>
      </form>
      <form class="form-inline top-form">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="name">
        </div>
      </form>
      <form class="form-inline top-form">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="mail@example.co.jp">
        </div>
      </form>
      <%= form_tag({:controller => "register_comp", :action => "index"},
                   {:method => "get", :class => "form-inline top-in-btn-form"}) do %>
        <div class="input-group">
          <input type="password" class="form-control" placeholder="password">
          <span class="input-group-btn">
            <button class="btn btn-warning" type="submit">登録</button>
          </span>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/register_comp/index.html.erb
<div class="container register-comp-container">
  <center>
    <%= image_tag "logo.png", :class => "top-logo" %>
  </center>
  <div align="center">
    <legend class="legend guidance">登録が完了しました</legend>
    <%= button_to "ログイン", {:controller => "authentication", :action => "index"},
                               :method => "get", :class => "btn btn-primary btn-lg"%>
  </div>
</div>

app/views/reset_password/index.html.erb
<div class="col-sm-4 col-md-4">
  <div class="container reset-pass-container">
    <legend class="legend update-pass-title">パスワードの変更</legend>
    <form>
      <div class="row update-pass-top-row">
        <div class="form-group col-sm-12 col-md-12 update-pass-id-form">
          <label for="input-id">ログインID</label>
          <div class="row">
            <div class="col-sm-12 col-md-12">
              <input type="text" class="form-control" id="input-id">
            </div>
          </div>
        </div>
        <div class="form-group col-sm-12 col-md-12 new-pass-form">
          <label for="input-new-pass">新しいパスワード</label>
          <div class="row">
            <div class="col-sm-12 col-md-12">
              <input type="password" class="form-control" id="input-new-pass">
            </div>
          </div>
        </div>
      </div>
    </form>
    <%= button_to "送信", {:controller => "authentication", :action => "index"},
                           :method => "get", :class => "btn btn-primary update-pass-btn"%>
  </div>
</div>

app/views/top/index.html.erb
<div class="container top-container">
  <center>
    <%= image_tag "logo.png", :class => "top-logo" %>
  </center>
  <div align="center">
    <legend class="legend top-guidance">ユーザー登録はお済みですか？</legend>
    <div class="button-field">
      <%= button_to "新規登録", {:controller => "register", :action => "index"},
                                 :method => "get", :class => "btn btn-warning btn-lg"%>
      <%= button_to "ログイン", {:controller => "authentication", :action => "index"},
                                 :method => "get", :class => "btn btn-primary btn-lg"%>
    </div>
  </div>
</div>
<%= link_to "パスワード変更", resetPassword_index_path, :class => "reset-pass-guidance"%>